### ISSUE TITLE
paper to-do 

### ISSUE THREAD

**Issue by naqvia** [rokitalab/clk1-splicing#13]
- [x] Response to reviewers document
- [x] Update manuscript with changes from above
- [x] Update relevant figure file and legend
- [x] Clean repo PRs
- [x] Upload data release files

**Comment by naqvia** [comment]
New datasets and input files used:
```
gtex-brain-under40-harmonized-splice-events-rmats.SE.tsv.gz
_1_SraRun_astrocytes_under40_hot.csv
normal-brain-isoform-expression-rsem-tpm.rds
GSE243682_normal_rna-isoform-expression-rsem-tpm.rds
gtex-harmonized-isoform-expression-rsem-tpm.rds
evodevo_rna-isoform-expression-rsem-tpm.rds
evodevo-histologies.tsv
ped-normal-brain-histologies.tsv
```

**Comment by jharenza** [comment]
@naqvia - looks like we forgot rmats for GSE73721, and release notes on s3 need an update.

**Comment by naqvia** [comment]
Completed
